// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqjnegefgyyfniphxusy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxxam5lZ2VmZ3l5Zm5pcGh4dXN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNTY1OTIsImV4cCI6MjA2MDczMjU5Mn0.u5RdVSr9MHJg9td1GzvEPH_0qu7KWPmjgzuUUqw47Mk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);